default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  primary:
    <<: *default
    database: elevate_api_development
  queue:
    <<: *default
    database: elevate_api_development_queueu
    migrations_paths: db/queue_migrate

test:
  primary:
    <<: *default
    database: elevate_api_test
  queue:
    <<: *default
    database: elevate_api_test
    migrations_paths: db/queue_migrate

production:
  <<: *default
  database: elevate_api_production
  username: elevate_api
  password: <%= ENV['ELEVATE_API_DATABASE_PASSWORD'] %>
